(() => {
  const plans = [
    { id:'A', name:'方案 A · 外乡人转化', note:'高压卷入后逐步获得归属；剧情情绪强，玩法体验在转正与双线调查后稳定上升。', nodes:[
      ['L01','警方追逐',3.8,4.2,'flow'],['L03','逃亡枪战',4.4,4.6,'both'],['L05','修车与氮气',2.5,3.5,''],['L06','1v1竞速',3.2,4.5,'flow'],['L11','金发牺牲',5.0,3.6,'climax'],['L12','加入帮派',4.0,2.8,''],['L14','复仇任务',4.4,4.0,''],['L17','正式转正',3.8,3.4,''],['L19','产业恢复',2.2,3.6,''],['L23','追查内奸',3.5,4.2,'flow'],['L26','绑架危机',4.8,3.8,'climax'],['L30','救援结案',4.5,4.6,'both'] ]},
    { id:'C', name:'方案 C · 本地打工崽', note:'先用连续可玩教学建立能力，再用帮派事件推高情绪；中段产业/调查双线形成体验高台。', nodes:[
      ['L01','警方追逐',3.6,4.1,'flow'],['L03','反伏击',4.2,4.5,'both'],['L05','修车装氮气',2.4,3.8,''],['L06','1v1竞速',3.1,4.7,'flow'],['L08','议会转正',3.7,2.9,''],['L11','建筑爆炸',4.5,3.0,'climax'],['L14','车辆强化',2.5,4.0,''],['L16','联手伏击',4.1,4.6,'flow'],['L17','晋升查内奸',3.3,3.4,''],['L20','双线开启',2.8,4.1,''],['L23','推关调查',3.4,4.5,'flow'],['L26','梅丽尔被掳',4.8,3.5,'climax'],['L29','追杀处决',4.7,4.7,'both'],['L30','会议结案',3.8,3.2,''] ]},
    { id:'D', name:'方案 D · 本地打工（叙事小改版）', note:'更早完成转正带来快速身份奖励；随后用竞速庆祝和建筑爆炸制造“释放—冲突”反差。', nodes:[
      ['L01','警方追逐',3.6,4.1,'flow'],['L03','反伏击',4.2,4.5,'both'],['L05','转正通知',2.7,3.0,''],['L06','修车装氮气',2.4,3.8,''],['L07','庆祝竞速',3.4,4.7,'flow'],['L09','建筑爆炸',4.6,3.0,'climax'],['L12','车辆强化',2.5,4.0,''],['L14','联手伏击',4.1,4.6,'flow'],['L17','晋升查内奸',3.3,3.4,''],['L20','双线开启',2.8,4.1,''],['L23','推关调查',3.4,4.5,'flow'],['L26','梅丽尔被掳',4.8,3.5,'climax'],['L29','追杀处决',4.7,4.7,'both'],['L30','会议结案',3.8,3.2,''] ]}
  ];
  const esc = value => String(value).replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const regression = values => {
    const n=values.length, sx=(n-1)*n/2, sy=values.reduce((a,b)=>a+b,0), sxx=(n-1)*n*(2*n-1)/6, sxy=values.reduce((a,b,i)=>a+i*b,0);
    const slope=(n*sxy-sx*sy)/(n*sxx-sx*sx), intercept=(sy-slope*sx)/n;
    return values.map((_,i)=>Math.max(0,Math.min(5,intercept+slope*i)));
  };
  const chart = plan => {
    const w=920,h=430,p={l:48,r:22,t:44,b:82}, iw=w-p.l-p.r, ih=h-p.t-p.b, step=iw/(plan.nodes.length-1);
    const xy=(v,i)=>[p.l+i*step,p.t+(5-v)/5*ih], line=key=>plan.nodes.map((n,i)=>xy(n[key],i).join(',')).join(' '), trend=regression(plan.nodes.map(n=>n[3])).map((v,i)=>xy(v,i).join(',')).join(' ');
    const grid=Array.from({length:6},(_,i)=>{const y=p.t+i*ih/5;return `<line x1="${p.l}" y1="${y}" x2="${w-p.r}" y2="${y}"/><text x="${p.l-12}" y="${y+4}">${5-i}</text>`}).join('');
    const marks=plan.nodes.map((n,i)=>{const [x,ye]=xy(n[2],i), [,yx]=xy(n[3],i); const marker=(n[4]==='climax'||n[4]==='both')?`<rect class="pf5-climax" x="${x-6}" y="${ye-6}" width="12" height="12" transform="rotate(45 ${x} ${ye})"/>`:''; const star=(n[4]==='flow'||n[4]==='both')?`<text class="pf5-star" x="${x}" y="${yx-10}">★</text>`:'';return `<g class="pf5-hit"><rect x="${x-step/2}" y="${p.t}" width="${step}" height="${ih}"/><title>${esc(n[0]+' '+n[1])}｜情绪 ${n[2]}｜体验 ${n[3]}</title></g>${marker}${star}<text class="pf5-x" x="${x}" y="${h-55}" transform="rotate(-35 ${x} ${h-55})">${esc(n[0]+' '+n[1])}</text>`}).join('');
    const delta=plan.nodes.at(-1)[3]-plan.nodes[0][3], verdict=delta>=.5?'上升':delta<=-.5?'下降':'持平';
    return `<article class="pf5-plan"><header><div><b>${esc(plan.name)}</b><p>${esc(plan.note)}</p></div><span>体验趋势：${verdict}（${plan.nodes[0][3].toFixed(1)} → ${plan.nodes.at(-1)[3].toFixed(1)}）</span></header><div class="pf5-chart"><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(plan.name)}心流模拟曲线"><g class="pf5-grid">${grid}</g><polyline class="pf5-emotion" points="${line(2)}"/><polyline class="pf5-experience" points="${line(3)}"/><polyline class="pf5-trend" points="${trend}"/>${marks}</svg></div></article>`;
  };
  const render = (doc, plan) => {
    if (!doc || doc.getElementById('dc-part-5')) return;
    const root=doc.getElementById('dobe-compressed-loops');
    if (!root) return;
    const section=doc.createElement('section'); section.id='dc-part-5'; section.className='dc-section pf5';
    section.innerHTML=`<h2>Part 5 · ${esc(plan.name)}心流曲线</h2><p class="pf5-note">沿用 early_stage 的双曲线表达：橙线为剧情情绪强度，蓝线为玩法体验强度，蓝色虚线为体验趋势。当前为基于策划案节点的模拟评分，不代表真实玩家测试结果；横轴仅使用关键剧情节点，不展示分钟时间轴，也不展示全局 LOOP。</p><div class="pf5-legend"><span><i class="emotion"></i>剧情情绪强度</span><span><i class="experience"></i>玩法体验强度</span><span><i class="trend"></i>体验趋势</span><span><b>◆</b>剧情高潮</span><span><b>★</b>心流高点</span></div><div class="pf5-list">${chart(plan)}</div>`;
    root.appendChild(section);
    const style=doc.createElement('style'); style.textContent=`#dc-part-5{margin-top:28px}.pf5-note{max-width:1100px;color:var(--muted-foreground);line-height:1.65}.pf5-legend{display:flex;flex-wrap:wrap;gap:10px 18px;margin:14px 0}.pf5-legend span{display:flex;align-items:center;gap:6px;font-size:12px}.pf5-legend i{width:25px;height:3px;border-radius:9px}.pf5-legend .emotion{background:#ef8a3a}.pf5-legend .experience{background:#3d86e8}.pf5-legend .trend{height:0;border-top:3px dashed #75a9ed}.pf5-legend b{color:#b54539}.pf5-list{display:grid;gap:18px}.pf5-plan{border:1px solid var(--border);border-radius:12px;background:var(--card);overflow:hidden}.pf5-plan header{display:flex;justify-content:space-between;gap:18px;padding:14px 16px;border-bottom:1px solid var(--border)}.pf5-plan header b{font-size:16px}.pf5-plan header p{margin:4px 0 0;color:var(--muted-foreground);font-size:12px}.pf5-plan header>span{flex:0 0 auto;align-self:center;padding:6px 9px;border-radius:999px;background:color-mix(in srgb,#3d86e8 12%,var(--card));color:#2d6dc5;font-size:11px;font-weight:800}.pf5-chart{padding:6px 12px 2px;overflow:hidden}.pf5-chart svg{display:block;width:100%;height:auto;min-height:330px;overflow:visible}.pf5-grid line{stroke:color-mix(in srgb,var(--border) 80%,transparent);stroke-width:1}.pf5-grid text{fill:var(--muted-foreground);font-size:10px;text-anchor:end}.pf5-emotion,.pf5-experience,.pf5-trend{fill:none;stroke-linejoin:round;stroke-linecap:round}.pf5-emotion{stroke:#ef8a3a;stroke-width:4}.pf5-experience{stroke:#3d86e8;stroke-width:4}.pf5-trend{stroke:#75a9ed;stroke-width:3;stroke-dasharray:10 7}.pf5-climax{fill:#d65748;stroke:#fff;stroke-width:2}.pf5-star{fill:#2675d8;stroke:#fff;stroke-width:2;paint-order:stroke;text-anchor:middle;font-size:18px}.pf5-x{fill:var(--muted-foreground);font-size:9px;text-anchor:end}.pf5-hit rect{fill:transparent;pointer-events:all}.pf5-hit:hover rect{fill:rgba(61,134,232,.08)}@media(max-width:800px){.pf5-plan header{display:block}.pf5-plan header>span{display:inline-block;margin-top:8px}.pf5-chart{overflow-x:auto}.pf5-chart svg{min-width:800px}}`;
    doc.head.appendChild(style);
    const nav=doc.querySelector('.dc-doc-nav ul, nav[aria-label="快速定位"] ul'); if(nav){const li=doc.createElement('li');li.className='dc-toc-item';li.innerHTML='<a class="dc-toc-link" data-level="2" href="#dc-part-5">Part 5 · 心流曲线</a>';nav.appendChild(li)}
  };
  const deepestDocument=frame=>{let doc=frame?.contentDocument;for(let depth=0;depth<5&&doc;depth+=1){const child=doc.querySelector('iframe');if(!child?.contentDocument)break;doc=child.contentDocument}return doc};
  const boot=()=>{const frames=[...document.querySelectorAll('iframe.plan-view')].filter(frame=>frame.id!=='plan-b'); if(!frames.length)return; const run=()=>frames.forEach(frame=>{try{const plan=plans.find(item=>item.id.toLowerCase()===frame.id.replace('plan-',''));if(plan)render(deepestDocument(frame),plan)}catch(_){}}); frames.forEach(frame=>frame.addEventListener('load',()=>setTimeout(run,0))); run(); let n=0; const timer=setInterval(()=>{run();if(frames.every(frame=>deepestDocument(frame)?.getElementById('dc-part-5'))||n++>80)clearInterval(timer)},250)};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
